Feature: Demo generated tracks

    User should be able to play each track that has been generated by the questionnaire.

Scenario: Play demo of generated tracks

    Given I am a listener who is on the playlist generator output page and have generated a playlist
    When I click on any of the songs
    Then a short sample of said song will be played